/** Family-pool bucket labels for the `golden` seed scenario (emoji-first). */
export const GOLDEN_BUCKET_NAMES = [
  '🏠 Rent',
  '🛒 Groceries',
  '⚡ Utilities',
  '💧 Water',
  '🔥 Gas & heating',
  '📶 Internet & phone',
  '🚗 Transportation',
  '⛽ Fuel',
  '🛡️ Insurance',
  '🏥 Health & medical',
  '💊 Pharmacy',
  '🦷 Dental',
  '👓 Vision',
  '🍽️ Dining out',
  '☕ Coffee & treats',
  '🎉 Fun & entertainment',
  '🎬 Streaming',
  '✈️ Travel',
  '🏖️ Vacation',
  '🎁 Gifts',
  '👕 Clothing',
  '🧒 Kids activities',
  '📚 Education',
  '🐾 Pets',
  '🔧 Home maintenance',
  '🌳 Yard & garden',
  '💼 Subscriptions',
  '💰 Emergency fund',
  '📈 Savings goals',
  '🧾 Misc & buffer',
] as const
